package org.sag.acminer.database.defusegraph.id;

import java.util.Objects;

import org.sag.acminer.phases.acminer.dw.DataWrapper;

import com.thoughtworks.xstream.annotations.XStreamAlias;

@XStreamAlias("DataWrapperPart")
public class DataWrapperPart implements Part {
	
	/* TODO DataWrapper needs to be updated to support xstream if we ever want to output these
	 * Currently, these are only generated by ACMiner not the DefUseGraph itself which does
	 * not output anything using xstream at the moment.
	 */
	@XStreamAlias("DataWrapper")
	private DataWrapper dw;

	public DataWrapperPart(DataWrapper dw) {
		this.dw = dw;
	}
	
	private DataWrapperPart(DataWrapperPart p) {
		this(p.dw.clone());
	}
	
	public String getCurString() {
		return dw.toString();
	}

	@Override
	public String getOrgString() {
		return dw.toString();
	}

	//For data wrappers we need to manipulate the identifier directly to change the string
	@Override
	public void setCurString(String curString) {}
	
	public String toString() {
		return getCurString();
	}
	
	public int hashCode() {
		return dw.hashCode();
	}
	
	public boolean equals(Object o) {
		if(this == o)
			return true;
		if(o == null || !(o instanceof DataWrapperPart))
			return false;
		return Objects.equals(dw, ((DataWrapperPart)o).dw);
	}
	
	public DataWrapper getDataWrapper() {
		return dw;
	}
	
	public DataWrapperPart clone() {
		return new DataWrapperPart(this);
	}
	
}
