name: ACMiner
data-accessor: org.sag.acminer.ACMinerDataAccessor
phases: [JimpleJar, EntryPoints, BinderGroups, BinderServices, VariedAnalysis, ExcludedElements, CallGraph, VariedCallGraphAnalysis, AccessControlMarker, ControlPredicateMarker, DefUseGraph, DefUseGraphDumpBeforeFilter, ControlPredicateFilter, DefUseGraphDumpAfterFilter, DefUseGraphMod, ACMinerDebug, ACMiner]
quick-options:
  default:
    description: "T1"
    enabled-phases:
      ACMiner: [enable, 'true']
  PreCallGraph:
    description: "T2"
    enabled-phases:
      ExcludedElements: [enable, 'true']
  DefUseGraphDump:
    description: "T3"
    enabled-phases:
      DefUseGraphDumpBeforeFilter: [enable, 'true']
      DefUseGraphDumpAfterFilter: [enable, 'true']
  DebugWithAllOption:
    description: "T4"
    enabled-phases:
      ACMinerDebug: [enable, 'true', All, 'true']
  AllDebugOptions:
    description: "T5"
    enabled-phases:
      DefUseGraphDumpBeforeFilter: [enable, 'true']
      DefUseGraphDumpAfterFilter: [enable, 'true']
      ACMinerDebug: [enable, 'true', All, 'true']
      ControlPredicateMarker: [EnableDebug, 'true']
      ControlPredicateFilter: [EnableDebug, 'true']
      ACMiner: [EnableDebug, 'true']
  VariedAnalysis:
    description: "T6"
    enabled-phases:
      VariedAnalysis: [enable, 'true']
  VariedCallGraphAnalysis:
    description: "T7"
    enabled-phases:
      VariedCallGraphAnalysis: [enable, 'true']
