name: ACMiner
description: "The authorization check miner phase group. Use this phase group if a run of ACMiner is desired."
data-accessor: org.sag.acminer.ACMinerDataAccessor
phases: [JimpleJar, EntryPoints, BinderGroups, BinderServices, VariedAnalysis, ExcludedElements, CallGraph, VariedCallGraphAnalysis, AccessControlMarker, ControlPredicateMarker, DefUseGraph, DefUseGraphDumpBeforeFilter, ControlPredicateFilter, DefUseGraphDumpAfterFilter, DefUseGraphMod, ACMinerDebug, ACMiner]
quick-options:
  default:
    description: "Runs ACMiner with default options for all required phases."
    enabled-phases:
      ACMiner: [enable, 'true']
  PreCallGraph:
    description: "Runs the phases of ACMiner that do not require a Call Graph to be generated."
    enabled-phases:
      ExcludedElements: [enable, 'true']
  DefUseGraphDump:
    description: "Enables the phases that dump the def-use graph both before and after the ControlPredicateFilter phase. Note that if this option is used alone, the ControlPredicateFilter phase will be the last of the normal ACMiner phases to be run."
    enabled-phases:
      DefUseGraphDumpBeforeFilter: [enable, 'true']
      DefUseGraphDumpAfterFilter: [enable, 'true']
  DebugWithAllOption:
    description: "Enables all options on the ACMinerDebug phase. If a option requires a value its default value is used. Note that if this option is used alone, the CallGraph phase will be the last of the normal ACMiner phases to be run."
    enabled-phases:
      ACMinerDebug: [enable, 'true', All, 'true']
  AllDebugOptions:
    description: "Runs ACMiner with all debugging options or phases enabled. The output from using this option is extremely verbose (large amount of data written to disk) and may result in extreme slow downs."
    enabled-phases:
      DefUseGraphDumpBeforeFilter: [enable, 'true']
      DefUseGraphDumpAfterFilter: [enable, 'true']
      ACMinerDebug: [enable, 'true', All, 'true']
      ControlPredicateMarker: [EnableDebug, 'true']
      ControlPredicateFilter: [EnableDebug, 'true']
      ACMiner: [EnableDebug, 'true']
  VariedAnalysis:
    description: "Enables the VariedAnalysis phase. TODO"
    enabled-phases:
      VariedAnalysis: [enable, 'true']
  VariedCallGraphAnalysis:
    description: "Enables the VariedCallGraphAnalysis phase. TODO"
    enabled-phases:
      VariedCallGraphAnalysis: [enable, 'true']
