-
  name: JimpleJar
  description: "From the files of a system image, this phase identifies the java class of the Android system, converts the classes to the Soot's intermediate representation Jimple, and creates a Jimple JAR to house the converted class files. This Jimple JAR contains all the classes analyzed in later analysis phases."
  handler: org.sag.sje.phases.jimplejar.JimpleJarHandler
  dependency-handlers: null
  root-path: sje-dir
  out-paths: sje_system-jimple-jar-file
  dependency-paths: [[work_system-img-zip-file, work_android-info-file], [work_system-class-jar-file]]
  other-paths: [sje_system-archives-zip-file, sje_system-jimple-framework-only-jar-file, sje_system-jimple-class-conflicts-zip-file, sje_work-dir, work_system-class-jar-file, work_system-img-zip-file, work_android-info-file, sje_system-class-jar-file, sje_framework-pkgs-file]
